version: "2"

formatters:
  enable:
    - gofumpt

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - revive
    - govet
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    lll:
      line-length: 140
    funlen:
      lines: 70
